version: "2"
services:
  redis:
    image: redis
  app:
    command: "yarn start"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=3000
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    restart: always
    container_name: kenya_dashboard
    depends_on:
      - redis
